import pygame

EMPTY,CORNER = 0,0
BLACK = 1
WHITE = -1
WIDTH, HEIGHT = 800, 800
BOARD_COLOR = (0, 180, 0)
ROWS, COLS = 8, 8
SQUARE_SIZE = WIDTH//ROWS
BLACK_COLOR = (0, 0, 0)
WHITE_COLOR = (255, 255, 255)
PIECE_RADIUS = SQUARE_SIZE // 2 - 5
THETA = 22

board = [
    [      2,     2, CORNER, CORNER, CORNER, CORNER,     2,     2,],
    [      2, CORNER, EMPTY, EMPTY, EMPTY, EMPTY, CORNER,     2,], 
    [  CORNER, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CORNER,], 
    [  CORNER, EMPTY, EMPTY, BLACK, WHITE, EMPTY, EMPTY, CORNER,], 
    [  CORNER, EMPTY, EMPTY, WHITE, BLACK, EMPTY, EMPTY, CORNER,], 
    [  CORNER, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, CORNER,], 
    [      2, CORNER, EMPTY, EMPTY, EMPTY, EMPTY, CORNER,     2,],
    [      2,     2, CORNER, CORNER, CORNER, CORNER,     2,     2,],
]

print(board)